import React, { useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import './TwoFactor.css';
import logoWhite from '../../assets/images/logo/logo_white.png';

const TwoFactor = () => {
  const inputsRef = useRef([]);
  const [code, setCode] = useState(['', '', '', '', '', '']);
  const navigate = useNavigate();

  const onChange = (index, value) => {
    if (!/^[0-9]?$/.test(value)) return;
    const next = [...code];
    next[index] = value;
    setCode(next);
    if (value && index < 5) {
      inputsRef.current[index + 1]?.focus();
    }
  };

  const onKeyDown = (index, e) => {
    if (e.key === 'Backspace' && !code[index] && index > 0) {
      const prev = inputsRef.current[index - 1];
      prev?.focus();
    }
  };

  const isComplete = code.every(c => c !== '');

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!isComplete) return;
    console.log('2FA code:', code.join(''));
    navigate('/dashboard');
  };

  return (
    <div className="twofactor-page">
      <div className="twofactor-logo-container">
        <img src={logoWhite} alt="TrustiChain Logo" className="twofactor-logo" />
        <div className="twofactor-brand-text">
          <h2 className="twofactor-brand-name">TrustiChain</h2>
          <p className="twofactor-tagline">XRP Ledger Escrow</p>
        </div>
      </div>

      <div className="twofactor-card">
        <h1 className="twofactor-header">Sign in using your authenticator app</h1>
        <p className="twofactor-description">
          Enter the 6-digit verification code generated by your <strong>authenticator app</strong>.
        </p>

        <form onSubmit={handleSubmit} className="twofactor-form">
          <div className="twofactor-inputs">
            {code.map((digit, i) => (
              <input
                key={i}
                ref={el => inputsRef.current[i] = el}
                type="tel"
                inputMode="numeric"
                maxLength={1}
                className={`twofactor-input ${i === 3 ? 'spaced' : ''}`}
                value={digit}
                onChange={(e) => onChange(i, e.target.value.replace(/\D/g, ''))}
                onKeyDown={(e) => onKeyDown(i, e)}
                required
              />
            ))}
          </div>

          <button type="submit" className="twofactor-primary-button" disabled={!isComplete}>
            Continue
          </button>
        </form>

        <div className="twofactor-footer">
          <Link to="/login" className="twofactor-footer-link">Sign in another way</Link>
        </div>
      </div>
    </div>
  );
};

export default TwoFactor;
